### ISSUE TITLE
New release, please

### ISSUE THREAD

**Issue by DpoBoceka** [influxdata/go-syslog#28]
Hello! Could you please roll out a new release, I'm planning to implement a new rfc3164 parser there https://github.com/Jeffail/benthos

**Comment by goller** [comment]
Hey @DpoBoceka !  Try out the new version!

The parser is fairly strict to the RFC right now.  However, let us know if you have messages that do not parse the way you would like.  We have a system of options that we can extend to give the parsing more flexibility.

**Comment by DpoBoceka** [comment]
Hey! I will :)

**Comment by DpoBoceka** [comment]
Thank you for your assistance, by the way)
